[package]
name = "template-engine"
version = "0.1.0"
edition = "2024"

[workspace]
resolver = "3"
members = ["template-engine-core","using-askama", "using-tera"]

[workspace.dependencies]
anyhow = "1.0.102"
axum = "0.8.9"
chrono = { version = "0.4.45", features = ["serde"] }
mime_guess = "2.0.5"
rust-embed = "8.11.0"
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.52.3", features = ["full"] }
uuid = { version = "1.23.2", features = ["serde", "v7"] }
